version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: "wednesday"
    time: "09:00"
    timezone: 'America/New_York'
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    day: "wednesday"
    time: "09:00"
    timezone: 'America/New_York'
  open-pull-requests-limit: 5
